<?php

// Make sure it's WordPress
if ( !defined( 'ABSPATH' ) ) {
	header( 'Status: 403 Forbidden' );
	header( 'HTTP/1.1 403 Forbidden' );
	exit();
}

// 2017-01-02 Tags are missing
function mn_p3_auto_scan_pages() {
	return array(
		'https://michaelnordmeyer.com/',
		'https://michaelnordmeyer.com/apple',
		'https://michaelnordmeyer.com/events',
		'https://michaelnordmeyer.com/miscellaneous',
		'https://michaelnordmeyer.com/technology',
		'https://michaelnordmeyer.com/web',
		'https://michaelnordmeyer.com/archives',
		'https://michaelnordmeyer.com/about',
		'https://michaelnordmeyer.com/web-tauglichkeit-qualitats-journalistischen-artikeln-kurzanalyse',
		'https://michaelnordmeyer.com/cant-wait-for-macworld-2008-keynote',
		'https://michaelnordmeyer.com/ipad-keyboard-annoyances',
		'https://michaelnordmeyer.com/wordpress-ios-behaves-nastily',
		'https://michaelnordmeyer.com/oneplus-2-specs-available-storage-dual-sim-slot',
		'https://michaelnordmeyer.com/storing-videos-amazon-cloud-drive',
		'https://michaelnordmeyer.com/delete-public-google-profile',
		'https://michaelnordmeyer.com/how-long-online-backup-take',
		'https://michaelnordmeyer.com/moving-an-opened-dropbox-file-can-mess-things-up',
		'https://michaelnordmeyer.com/ghost-vs-wordpress',
		'https://michaelnordmeyer.com/icloud-photo-library-photos',
		'https://michaelnordmeyer.com/icloud-drive-display-files',
		'https://michaelnordmeyer.com/blogging-app-desk-looks-cool-behaves-badly',
		'https://michaelnordmeyer.com/downloading-facebook-data-ever-work',
		'https://michaelnordmeyer.com/free-space-iphone-64gb-ios-8',
		'https://michaelnordmeyer.com/icloud-photo-library-photos',
		'https://michaelnordmeyer.com/icloud-drive-display-files',
		'https://michaelnordmeyer.com/blogging-app-desk-looks-cool-behaves-badly',
		'https://michaelnordmeyer.com/downloading-facebook-data-ever-work',
		'https://michaelnordmeyer.com/free-space-iphone-64gb-ios-8',
		'https://michaelnordmeyer.com/safaris-icloud-keychain-security-problem',
		'https://michaelnordmeyer.com/easily-create-strong-passwords',
		'https://michaelnordmeyer.com/combing-7-years-tweets',
		'https://michaelnordmeyer.com/opt-out-interest-based-ads-google',
		'https://michaelnordmeyer.com/disable-google-account-history-keep-privacy',
		'https://michaelnordmeyer.com/wordpress-featured-image-plugins',
		'https://michaelnordmeyer.com/quitting-google-whatsapp-buzzfeed-huffpost',
		'https://michaelnordmeyer.com/quitting-twitter',
		'https://michaelnordmeyer.com/mailbox-mac-os-x-beta',
		'https://michaelnordmeyer.com/icloud-email-address',
		'https://michaelnordmeyer.com/of-mice-and-men-my-first-barcamp',
		'https://michaelnordmeyer.com/internet-speed-test-mobile-dsl-cable',
		'https://michaelnordmeyer.com/javascript-blocklists-removing-ads-notifications',
		'https://michaelnordmeyer.com/apple-time-capsule-power-consumption',
		'https://michaelnordmeyer.com/infinite-scrolling-is-evil',
		'https://michaelnordmeyer.com/social-medias-worst-habit-crossposting',
		'https://michaelnordmeyer.com/difference-apple-airport-express-extreme-time-capsule',
		'https://michaelnordmeyer.com/difference-macbook-air-thunderbolt-vs-macbook-pro-retina-2012',
		'https://michaelnordmeyer.com/speed-thunderbolt-ethernet-adapter-macbook-air-macbook-pro-retina',
		'https://michaelnordmeyer.com/fast-gigabit-wireless-802-11ac-802-11ad-problems',
		'https://michaelnordmeyer.com/hd-difference-quality-720p-1080p-resolution',
		'https://michaelnordmeyer.com/amazon-kindle-e-book-backup',
		'https://michaelnordmeyer.com/speed-macbook-air-usb-ethernet-adapter',
		'https://michaelnordmeyer.com/difference-macbook-air-thunderbolt-vs-macbook-pro-2011',
		'https://michaelnordmeyer.com/tedxhamburg-2011',
		'https://michaelnordmeyer.com/personal-hotspot-iphone-ipad-ipod-touch',
		'https://michaelnordmeyer.com/macbook-air-2010-macbook-pro-differences-omissions',
		'https://michaelnordmeyer.com/community-building-top-5',
		'https://michaelnordmeyer.com/apples-wwdc-2010-iphone-ipad-gold-rush',
		'https://michaelnordmeyer.com/tedxhamburg-2010',
		'https://michaelnordmeyer.com/first-impressions-next-conference-2010',
/*		'https://michaelnordmeyer.com/wepad-wetab-recap',
		'https://michaelnordmeyer.com/web-tauglichkeit-qualitats-journalistischen-artikeln-kurzanalyse',
		'https://michaelnordmeyer.com/makerbot-3d-printer-open-source-designs',
		'https://michaelnordmeyer.com/republica-2010-modern-technology-failure',
		'https://michaelnordmeyer.com/google-chrome-extensions-hackathon-hamburg-aftermath',
		'https://michaelnordmeyer.com/google-chrome-extensions-hackathon-hamburg',
		'https://michaelnordmeyer.com/tedxberlin',
		'https://michaelnordmeyer.com/oembed-presentation',
		'https://michaelnordmeyer.com/bill-gates-wive-melinda-an-awesome-comedy',
		'https://michaelnordmeyer.com/green-tea-tasting-web-2-0-style',
		'https://michaelnordmeyer.com/simpsons-mock-apple',
		'https://michaelnordmeyer.com/cool-blogging-and-twitter-comedy',
		'https://michaelnordmeyer.com/dnadigital-open-space',
		'https://michaelnordmeyer.com/next08-conference-afterthoughts',
		'https://michaelnordmeyer.com/kick-off-elevator-pitch-at-next08',
		'https://michaelnordmeyer.com/microsoft-blogger-connection-kickoff',
		'https://michaelnordmeyer.com/next08-conference-get-realtime-coming-tomorrow',
		'https://michaelnordmeyer.com/opencoffee-club-and-cutting-some-slack',
		'https://michaelnordmeyer.com/barcamp-hannover-2008',
		'https://michaelnordmeyer.com/wordpress-built-in-visual-editor-doesnt-like-safari',
		'https://michaelnordmeyer.com/why-i-chose-wordpress-thoughts-from-wordcamp-08',
		'https://michaelnordmeyer.com/wordcamp-08-in-hamburg',
		'https://michaelnordmeyer.com/cant-wait-for-macworld-2008-keynote',
		'https://michaelnordmeyer.com/plugins-and-themes-and-skins-and-no-sleep',
		'https://michaelnordmeyer.com/vodafone-germanys-mobile-internet-sucks',
		'https://michaelnordmeyer.com/wow-im-live',
		'https://michaelnordmeyer.com/wp-admin',
		'https://michaelnordmeyer.com/wp-admin/edit.php',
		'https://michaelnordmeyer.com/wp-admin/upload.php',
*/	);
}
add_filter( 'p3_automatic_scan_urls', 'mn_p3_auto_scan_pages' );
add_filter( 'show_admin_bar', '__return_false' );
show_admin_bar( false );
